version: '3'

services:
  anke-to:
    build:
      context: ..
      dockerfile: development/Dockerfile
    environment:
      MARIADB_USERNAME: root
      MARIADB_PASSWORD: password
      MARIADB_HOSTNAME: mysql
      MARIADB_DATABASE: anke-to
    ports:
      - '1323:1323'
    volumes:
      - '../:/go/src/git.trapti.tech/SysAd/anke-to'
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.3.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: anke-to
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    expose:
      - '3306'
    ports:
      - '3306:3306'
