name: Release

on:
  push:
    branches: 
      - release

env:
  IMAGE_NAME: anke-to

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: traPtitech
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.pkg.github.com/traptitech/anke-to/${IMAGE_NAME}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
